In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("Datasets/pima-indians-diabetes.csv")

In [3]:
df.head()

   6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [4]:
df.rename(columns={'6':'Pregnancies','148':'Glucose','72':'BloodPressure','35':'SkinThickness','0':'Insulin','33.6':'BMI','0.627':'DiabetesPredigreeFunction','50':'Age','1':'Outcome'}, inplace=True)

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPredigreeFunction,Age,Outcome
0,1,85,66,29,0,26.6,0.351,31,0
1,8,183,64,0,0,23.3,0.672,32,1
2,1,89,66,23,94,28.1,0.167,21,0
3,0,137,40,35,168,43.1,2.288,33,1
4,5,116,74,0,0,25.6,0.201,30,0

In [6]:
df.corr()['Outcome']

Pregnancies                  0.221087
Glucose                      0.465856
BloodPressure                0.064882
SkinThickness                0.073265
Insulin                      0.131984
BMI                          0.292695
DiabetesPredigreeFunction    0.173245
Age                          0.236417
Outcome                      1.000000
Name: Outcome, dtype: float64

In [7]:
X= df.iloc[:,:-1].values
y= df.iloc[:,-1].values

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
X= scaler.fit_transform(X)

In [11]:
X.shape

(767, 8)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state= 1)

In [13]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [14]:
model = Sequential()

model.add(Dense(32, activation ='relu', input_dim=8))
model.add(Dense(1, activation ='sigmoid'))

model.compile(optimizer= 'Adam', loss= 'binary_crossentropy', metrics=['accuracy'])

C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data= (X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.4845 - loss: 0.7059 - val_accuracy: 0.5584 - val_loss: 0.6779
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6215 - loss: 0.6446 - val_accuracy: 0.6818 - val_loss: 0.6257
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7080 - loss: 0.6016 - val_accuracy: 0.7078 - val_loss: 0.5811
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7471 - loss: 0.5686 - val_accuracy: 0.7403 - val_loss: 0.5515
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7553 - loss: 0.5445 - val_accuracy: 0.7532 - val_loss: 0.5313
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7504 - loss: 0.5265 - val_accuracy: 0.7662 - val_loss: 0.5142
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7569 - loss: 0.5125 - val_accuracy: 0.7662 - val_loss: 0.5035
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7602 - loss: 0.5011 - val_accuracy: 0.7727 - val_loss: 0.4956
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7618 - loss: 0.4923 - val_accuracy: 0.7727 - val_loss: 0.4890
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7716 - loss: 0.4849 - val_accuracy: 0.7857 - val_loss: 0.4829
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7732 - loss: 0.4786 - val_accuracy: 0.7792 - val_loss: 0.4792
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7732 - loss: 0.4738 - val_accuracy: 0.7727 - val_loss: 0.4745
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7732 - loss: 0.4689 - val_accuracy: 0.7662 - val_loss: 0.4728
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7716 - loss: 0.4655 - val_accuracy: 0.7662 - val_loss: 0.4704
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7732 - loss: 0.4627 - val_accuracy: 0.7597 - val_loss: 0.4684
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7781 - loss: 0.4601 - val_accuracy: 0.7597 - val_loss: 0.4674
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7765 - loss: 0.4583 - val_accuracy: 0.7662 - val_loss: 0.4664
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7814 - loss: 0.4559 - val_accuracy: 0.7532 - val_loss: 0.4667
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7781 - loss: 0.4552 - val_accuracy: 0.7597 - val_loss: 0.4676
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7814 - loss: 0.4525 - val_accuracy: 0.7597 - val_loss: 0.4667
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7830 - loss: 0.4520 - val_accuracy: 0.7597 - val_loss: 0.4664
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7847 - loss: 0.4500 - val_accuracy: 0.7597 - val_loss: 0.4657
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7847 - loss: 0.4485 - val_accuracy: 0.7662 - val_loss: 0.4643
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7830 - loss: 0.4471 - val_accuracy: 0.7597 - val_loss: 0.4645
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7847 - loss: 0.4467 - val_accuracy: 0.7662 - val_loss: 0.4648
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7814 - loss: 0.4455 - val_accuracy: 0.7662 - val_loss: 0.4648
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7814 - loss: 0.4452 - val_accuracy: 0.7662 - val_loss: 0.4643
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7781 - loss: 0.4437 - val_accuracy: 0.7662 - val_loss: 0.4652
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7830 - loss: 0.4428 - val_accuracy: 0.7662 - val_loss: 0.4646
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7798 - loss: 0.4422 - val_accuracy: 0.7662 - val_loss: 0.4650
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7863 - loss: 0.4415 - val_accuracy: 0.7662 - val_loss: 0.4645
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7863 - loss: 0.4409 - val_accuracy: 0.7662 - val_loss: 0.4642
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4406 - val_accuracy: 0.7662 - val_loss: 0.4657
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7896 - loss: 0.4392 - val_accuracy: 0.7597 - val_loss: 0.4658
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7847 - loss: 0.4389 - val_accuracy: 0.7662 - val_loss: 0.4665
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7863 - loss: 0.4380 - val_accuracy: 0.7662 - val_loss: 0.4657
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7863 - loss: 0.4375 - val_accuracy: 0.7662 - val_loss: 0.4647
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7863 - loss: 0.4365 - val_accuracy: 0.7662 - val_loss: 0.4648
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7863 - loss: 0.4361 - val_accuracy: 0.7662 - val_loss: 0.4649
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7896 - loss: 0.4356 - val_accuracy: 0.7727 - val_loss: 0.4647
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4351 - val_accuracy: 0.7857 - val_loss: 0.4640
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7879 - loss: 0.4339 - val_accuracy: 0.7597 - val_loss: 0.4647
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7879 - loss: 0.4343 - val_accuracy: 0.7662 - val_loss: 0.4642
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7863 - loss: 0.4336 - val_accuracy: 0.7662 - val_loss: 0.4633
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4329 - val_accuracy: 0.7662 - val_loss: 0.4638
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7879 - loss: 0.4322 - val_accuracy: 0.7662 - val_loss: 0.4638
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7879 - loss: 0.4324 - val_accuracy: 0.7727 - val_loss: 0.4645
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7879 - loss: 0.4314 - val_accuracy: 0.7727 - val_loss: 0.4614
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4311 - val_accuracy: 0.7792 - val_loss: 0.4614
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4306 - val_accuracy: 0.7727 - val_loss: 0.4624
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4307 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4299 - val_accuracy: 0.7857 - val_loss: 0.4613
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4290 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4282 - val_accuracy: 0.7857 - val_loss: 0.4617
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4279 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4277 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4279 - val_accuracy: 0.7792 - val_loss: 0.4612
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4274 - val_accuracy: 0.7727 - val_loss: 0.4616
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4272 - val_accuracy: 0.7792 - val_loss: 0.4608
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7896 - loss: 0.4260 - val_accuracy: 0.7857 - val_loss: 0.4600
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4260 - val_accuracy: 0.7857 - val_loss: 0.4604
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7896 - loss: 0.4256 - val_accuracy: 0.7857 - val_loss: 0.4606
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7847 - loss: 0.4250 - val_accuracy: 0.7792 - val_loss: 0.4604
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7879 - loss: 0.4244 - val_accuracy: 0.7727 - val_loss: 0.4609
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7896 - loss: 0.4238 - val_accuracy: 0.7662 - val_loss: 0.4620
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4233 - val_accuracy: 0.7792 - val_loss: 0.4613
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7879 - loss: 0.4232 - val_accuracy: 0.7857 - val_loss: 0.4617
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4226 - val_accuracy: 0.7792 - val_loss: 0.4628
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4225 - val_accuracy: 0.7727 - val_loss: 0.4622
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4224 - val_accuracy: 0.7792 - val_loss: 0.4612
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4218 - val_accuracy: 0.7857 - val_loss: 0.4616
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4217 - val_accuracy: 0.7792 - val_loss: 0.4621
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4209 - val_accuracy: 0.7727 - val_loss: 0.4623
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4208 - val_accuracy: 0.7727 - val_loss: 0.4623
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4204 - val_accuracy: 0.7727 - val_loss: 0.4611
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7977 - loss: 0.4204 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4196 - val_accuracy: 0.7727 - val_loss: 0.4614
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4193 - val_accuracy: 0.7727 - val_loss: 0.4617
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4190 - val_accuracy: 0.7727 - val_loss: 0.4608
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4188 - val_accuracy: 0.7727 - val_loss: 0.4609
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4185 - val_accuracy: 0.7727 - val_loss: 0.4609
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4185 - val_accuracy: 0.7727 - val_loss: 0.4612
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7977 - loss: 0.4176 - val_accuracy: 0.7792 - val_loss: 0.4610
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7961 - loss: 0.4187 - val_accuracy: 0.7792 - val_loss: 0.4613
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7961 - loss: 0.4177 - val_accuracy: 0.7727 - val_loss: 0.4608
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4170 - val_accuracy: 0.7727 - val_loss: 0.4612
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4172 - val_accuracy: 0.7792 - val_loss: 0.4595
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7961 - loss: 0.4168 - val_accuracy: 0.7857 - val_loss: 0.4597
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4155 - val_accuracy: 0.7727 - val_loss: 0.4609
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4159 - val_accuracy: 0.7792 - val_loss: 0.4614
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4157 - val_accuracy: 0.7792 - val_loss: 0.4607
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7928 - loss: 0.4155 - val_accuracy: 0.7662 - val_loss: 0.4613
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7977 - loss: 0.4143 - val_accuracy: 0.7792 - val_loss: 0.4607
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7961 - loss: 0.4146 - val_accuracy: 0.7857 - val_loss: 0.4612
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4137 - val_accuracy: 0.7792 - val_loss: 0.4611
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4151 - val_accuracy: 0.7922 - val_loss: 0.4590
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4136 - val_accuracy: 0.7792 - val_loss: 0.4588
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7961 - loss: 0.4134 - val_accuracy: 0.7727 - val_loss: 0.4585
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4125 - val_accuracy: 0.7857 - val_loss: 0.4579
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7977 - loss: 0.4126 - val_accuracy: 0.7857 - val_loss: 0.4590

### Using Keras Tuner

#### 1- How to select appropriate optimizer
#### 2- How to select no. of nodes in a layer
#### 3- How to select no. of hidden layers
#### 4- All in one model

In [16]:
pip install keras-tuner

Requirement already satisfied: keras-tuner in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.4.8)
Requirement already satisfied: keras in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras-tuner) (3.15.1)
Requirement already satisfied: packaging in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras-tuner) (2.34.2)
Requirement already satisfied: kt-legacy in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras-tuner) (1.84.0)
Requirement already satisfied: protobuf in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras-tuner) (7.36.2)
Requirement already satisfied: typing-extensions~=4.12 in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras->keras-tuner) (2.5.0)
Requirement already satisfied: numpy in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras->keras-tuner) (2.5.3)
Requirement already satisfied: rich in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras->keras-tuner) (15.0.0)
Requirement already satisfied: namex in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->keras-tuner) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->keras-tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->keras-tuner) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import kerastuner as kt

C:\Users\Rihan\AppData\Local\Temp\ipykernel_37020\1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [18]:
# selecting optimizer

def build_model(hp):

    model = Sequential()

    model.add(Dense(32, activation ='relu', input_dim=8))
    model.add(Dense(1, activation ='sigmoid'))

    optimizer= hp.Choice('optimizer', ['sgd','adam','rmsprop','adadelta'])

    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [21]:
tuner= kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5,directory='tuner_results',
    project_name='optimizer_search',
    overwrite=True)

In [22]:
tuner.search(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 03s]
val_accuracy: 0.5259740352630615

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 12s

In [23]:
print(tuner.get_best_hyperparameters(1)[0].values)

best_model = tuner.get_best_models(1)[0]

{'optimizer': 'rmsprop'}

C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\keras\src\saving\saving_lib.py:869: UserWarning: Skipping variable loading for optimizer 'rm_sprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(store)

In [28]:
tuner.results_summary()

Results summary
Results in tuner_results\optimizer_search
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 1 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.798701286315918

Trial 2 summary
Hyperparameters:
optimizer: adam
Score: 0.7727272510528564

Trial 0 summary
Hyperparameters:
optimizer: sgd
Score: 0.7207792401313782

Trial 3 summary
Hyperparameters:
optimizer: adadelta
Score: 0.5259740352630615

In [29]:
print(best_model.optimizer.get_config())

{'name': 'rm_sprop', 'learning_rate': 0.0010000000474974513, 'weight_decay': None, 'clipnorm': None, 'global_clipnorm': None, 'clipvalue': None, 'use_ema': False, 'ema_momentum': 0.99, 'ema_overwrite_frequency': None, 'loss_scale_factor': None, 'gradient_accumulation_steps': None, 'rho': 0.9, 'momentum': 0.0, 'epsilon': 1e-07, 'centered': False}

In [31]:
model.fit(X_train, y_train, batch_size=32, epochs= 100, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7961 - loss: 0.4128 - val_accuracy: 0.7857 - val_loss: 0.4591
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7961 - loss: 0.4121 - val_accuracy: 0.7792 - val_loss: 0.4586
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7961 - loss: 0.4118 - val_accuracy: 0.7857 - val_loss: 0.4590
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4116 - val_accuracy: 0.7857 - val_loss: 0.4584
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7977 - loss: 0.4109 - val_accuracy: 0.7857 - val_loss: 0.4595
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7977 - loss: 0.4112 - val_accuracy: 0.7727 - val_loss: 0.4594
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7961 - loss: 0.4112 - val_accuracy: 0.7727 - val_loss: 0.4600
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4102 - val_accuracy: 0.7727 - val_loss: 0.4599
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4101 - val_accuracy: 0.7792 - val_loss: 0.4608
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7977 - loss: 0.4100 - val_accuracy: 0.7792 - val_loss: 0.4613
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4095 - val_accuracy: 0.7792 - val_loss: 0.4621
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7928 - loss: 0.4096 - val_accuracy: 0.7857 - val_loss: 0.4622
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4091 - val_accuracy: 0.7792 - val_loss: 0.4626
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8026 - loss: 0.4082 - val_accuracy: 0.7792 - val_loss: 0.4621
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4091 - val_accuracy: 0.7727 - val_loss: 0.4632
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4082 - val_accuracy: 0.7727 - val_loss: 0.4623
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4078 - val_accuracy: 0.7857 - val_loss: 0.4610
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4072 - val_accuracy: 0.7727 - val_loss: 0.4612
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4075 - val_accuracy: 0.7792 - val_loss: 0.4620
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8026 - loss: 0.4068 - val_accuracy: 0.7662 - val_loss: 0.4615
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8042 - loss: 0.4065 - val_accuracy: 0.7727 - val_loss: 0.4620
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8042 - loss: 0.4063 - val_accuracy: 0.7792 - val_loss: 0.4618
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8026 - loss: 0.4072 - val_accuracy: 0.7857 - val_loss: 0.4623
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8059 - loss: 0.4066 - val_accuracy: 0.7792 - val_loss: 0.4622
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8075 - loss: 0.4054 - val_accuracy: 0.7727 - val_loss: 0.4625
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4052 - val_accuracy: 0.7857 - val_loss: 0.4616
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8026 - loss: 0.4050 - val_accuracy: 0.7857 - val_loss: 0.4625
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4046 - val_accuracy: 0.7857 - val_loss: 0.4638
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8042 - loss: 0.4051 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8042 - loss: 0.4041 - val_accuracy: 0.7857 - val_loss: 0.4623
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4034 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4037 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4038 - val_accuracy: 0.7987 - val_loss: 0.4646
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8026 - loss: 0.4031 - val_accuracy: 0.7987 - val_loss: 0.4634
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8026 - loss: 0.4027 - val_accuracy: 0.7857 - val_loss: 0.4633
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4027 - val_accuracy: 0.7922 - val_loss: 0.4646
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8059 - loss: 0.4025 - val_accuracy: 0.7922 - val_loss: 0.4652
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8075 - loss: 0.4021 - val_accuracy: 0.7922 - val_loss: 0.4654
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8091 - loss: 0.4015 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8075 - loss: 0.4011 - val_accuracy: 0.7857 - val_loss: 0.4648
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8091 - loss: 0.4013 - val_accuracy: 0.7922 - val_loss: 0.4651
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8091 - loss: 0.4005 - val_accuracy: 0.7792 - val_loss: 0.4655
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8108 - loss: 0.4008 - val_accuracy: 0.7857 - val_loss: 0.4664
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8059 - loss: 0.4003 - val_accuracy: 0.7987 - val_loss: 0.4663
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8075 - loss: 0.4001 - val_accuracy: 0.7922 - val_loss: 0.4655
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8091 - loss: 0.3996 - val_accuracy: 0.7857 - val_loss: 0.4654
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8091 - loss: 0.3998 - val_accuracy: 0.7857 - val_loss: 0.4657
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8059 - loss: 0.3995 - val_accuracy: 0.7987 - val_loss: 0.4670
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8059 - loss: 0.4011 - val_accuracy: 0.7987 - val_loss: 0.4683
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8075 - loss: 0.3992 - val_accuracy: 0.7922 - val_loss: 0.4673
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8091 - loss: 0.3988 - val_accuracy: 0.8052 - val_loss: 0.4675
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8042 - loss: 0.3985 - val_accuracy: 0.8052 - val_loss: 0.4688
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8124 - loss: 0.3986 - val_accuracy: 0.7922 - val_loss: 0.4697
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8042 - loss: 0.3989 - val_accuracy: 0.7987 - val_loss: 0.4701
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8108 - loss: 0.3987 - val_accuracy: 0.7922 - val_loss: 0.4691
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8124 - loss: 0.3982 - val_accuracy: 0.7922 - val_loss: 0.4677
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8075 - loss: 0.3980 - val_accuracy: 0.7857 - val_loss: 0.4673
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8173 - loss: 0.3978 - val_accuracy: 0.7857 - val_loss: 0.4670
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8108 - loss: 0.3973 - val_accuracy: 0.7792 - val_loss: 0.4669
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8140 - loss: 0.3972 - val_accuracy: 0.7857 - val_loss: 0.4681
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8189 - loss: 0.3971 - val_accuracy: 0.7792 - val_loss: 0.4682
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8157 - loss: 0.3966 - val_accuracy: 0.7792 - val_loss: 0.4694
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8108 - loss: 0.3966 - val_accuracy: 0.7922 - val_loss: 0.4704
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8075 - loss: 0.3959 - val_accuracy: 0.7987 - val_loss: 0.4697
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8075 - loss: 0.3955 - val_accuracy: 0.7922 - val_loss: 0.4700
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8173 - loss: 0.3960 - val_accuracy: 0.7857 - val_loss: 0.4703
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8189 - loss: 0.3955 - val_accuracy: 0.7922 - val_loss: 0.4703
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8140 - loss: 0.3953 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8091 - loss: 0.3948 - val_accuracy: 0.8117 - val_loss: 0.4700
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8042 - loss: 0.3945 - val_accuracy: 0.8117 - val_loss: 0.4721
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8140 - loss: 0.3943 - val_accuracy: 0.7987 - val_loss: 0.4733
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8157 - loss: 0.3946 - val_accuracy: 0.7987 - val_loss: 0.4730
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8173 - loss: 0.3951 - val_accuracy: 0.7922 - val_loss: 0.4729
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8124 - loss: 0.3941 - val_accuracy: 0.7987 - val_loss: 0.4733
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8157 - loss: 0.3937 - val_accuracy: 0.7857 - val_loss: 0.4749
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8189 - loss: 0.3936 - val_accuracy: 0.7857 - val_loss: 0.4737
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8108 - loss: 0.3934 - val_accuracy: 0.7922 - val_loss: 0.4722
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8108 - loss: 0.3934 - val_accuracy: 0.7987 - val_loss: 0.4727
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8173 - loss: 0.3933 - val_accuracy: 0.7922 - val_loss: 0.4717
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8157 - loss: 0.3933 - val_accuracy: 0.7727 - val_loss: 0.4704
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8157 - loss: 0.3925 - val_accuracy: 0.7922 - val_loss: 0.4716
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8157 - loss: 0.3925 - val_accuracy: 0.8052 - val_loss: 0.4727
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8140 - loss: 0.3918 - val_accuracy: 0.7987 - val_loss: 0.4737
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8124 - loss: 0.3917 - val_accuracy: 0.7987 - val_loss: 0.4740
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8206 - loss: 0.3918 - val_accuracy: 0.7857 - val_loss: 0.4746
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8157 - loss: 0.3920 - val_accuracy: 0.7857 - val_loss: 0.4744
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8222 - loss: 0.3926 - val_accuracy: 0.7727 - val_loss: 0.4761
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8189 - loss: 0.3920 - val_accuracy: 0.7857 - val_loss: 0.4774
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8189 - loss: 0.3915 - val_accuracy: 0.7922 - val_loss: 0.4775
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8173 - loss: 0.3913 - val_accuracy: 0.7857 - val_loss: 0.4741
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8157 - loss: 0.3914 - val_accuracy: 0.7857 - val_loss: 0.4738
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8124 - loss: 0.3906 - val_accuracy: 0.7857 - val_loss: 0.4722
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8140 - loss: 0.3906 - val_accuracy: 0.7857 - val_loss: 0.4732
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8173 - loss: 0.3905 - val_accuracy: 0.7792 - val_loss: 0.4740

In [32]:
tuner.results_summary()

Results summary
Results in tuner_results\optimizer_search
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 1 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.798701286315918

Trial 2 summary
Hyperparameters:
optimizer: adam
Score: 0.7727272510528564

Trial 0 summary
Hyperparameters:
optimizer: sgd
Score: 0.7207792401313782

Trial 3 summary
Hyperparameters:
optimizer: adadelta
Score: 0.5259740352630615

In [66]:
def build_model(hp):
    model = Sequential()

    # Tune the number of hidden neurons
    units = hp.Int('units', min_value=8, max_value=128, step=8)

    model.add(Dense(units, activation='relu', input_dim=8))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [67]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=10,
    directory='tuner_results',
    project_name='neuron_tuning',
    overwrite=True
)

In [68]:
tuner.search(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Trial 10 Complete [00h 00m 03s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 32s

In [69]:
tuner.get_best_hyperparameters()[0].values

{'units': 128}

In [70]:
best_hp = tuner.get_best_hyperparameters(1)[0]
print("Best number of neurons:", best_hp.get('units'))

Best number of neurons: 128

In [72]:
#No of layers

def build_model(hp):
    model = Sequential()

    num_layers = hp.Int('num_layers', 1, 5, step=1)

    model.add(Dense(32, activation='relu', input_shape=(8,)))

    for _ in range(num_layers - 1):
        model.add(Dense(32, activation='relu'))

    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [73]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='tuner_results',
    project_name='layer_tuning',
    overwrite=True
)

tuner.search(
    X_train, y_train,
    epochs=10,
    validation_data=(X_test, y_test)
)

print(tuner.get_best_hyperparameters(1)[0].values)

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 19s
{'num_layers': 5}

In [74]:
def build_model(hp):
    model = Sequential()

    # Tune number of hidden layers
    num_layers = hp.Int('num_layers', min_value=1, max_value=5)

    # Tune neurons in each hidden layer
    for i in range(num_layers):
        units = hp.Int(
            f'units_{i}',
            min_value=8,
            max_value=128,
            step=8
        )

        if i == 0:
            model.add(Dense(
                units=units,
                activation='relu',
                input_shape=(8,)
            ))
        else:
            model.add(Dense(units=units, activation='relu'))

    # Tune optimizer
    optimizer_name = hp.Choice(
        'optimizer',
        ['adam', 'sgd', 'rmsprop', 'adadelta']
    )

    # Tune learning rate
    learning_rate = hp.Choice(
        'learning_rate',
        [0.001, 0.01, 0.1]
    )

    if optimizer_name == 'adam':
        optimizer = keras.optimizers.Adam(learning_rate=learning_rate)
    elif optimizer_name == 'sgd':
        optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
    elif optimizer_name == 'rmsprop':
        optimizer = keras.optimizers.RMSprop(learning_rate=learning_rate)
    else:
        optimizer = keras.optimizers.Adadelta(learning_rate=learning_rate)

    # Output layer for binary classification
    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [75]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=10,
    directory='tuner_results',
    project_name='all_in_one',
    overwrite=True
)

In [76]:
tuner.search(
    X_train,
    y_train,
    epochs=10,
    validation_data=(X_test, y_test)
)

Trial 10 Complete [00h 00m 03s]
val_accuracy: 0.7402597665786743

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 35s

In [77]:
# Display best hyperparameters
best_hp = tuner.get_best_hyperparameters(1)[0]
print("Best hyperparameters:", best_hp.values)

# Get the best model
best_model = tuner.get_best_models(1)[0]
best_model.summary()

Best hyperparameters: {'num_layers': 3, 'units_0': 80, 'optimizer': 'adam', 'learning_rate': 0.001, 'units_1': 112, 'units_2': 16, 'units_3': 128, 'units_4': 120}

C:\Users\Rihan\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\keras\src\saving\saving_lib.py:869: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 18 variables.
  saveable.load_own_variables(store)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 80)                  │             720 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 112)                 │           9,072 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 16)                  │           1,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 11,617 (45.38 KB)

 Trainable params: 11,617 (45.38 KB)

 Non-trainable params: 0 (0.00 B)